image: "python:3.7"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V
  - pip3 install pipenv

test:
  script:
    - ls
    - pipenv install --dev --deploy --system --ignore-pipfile
    - pytest
